---


named_vlans:
  - { vlan_id: 100, vlan_name: management }
  - { vlan_id: 101, vlan_name: wireless }
  - { vlan_id: 102, vlan_name: guest }
  - { vlan_id: 103, vlan_name: wired }
  - { vlan_id: 104, vlan_name: voice }
    
l3_vlans:
  - { vlan_id: 100, description: Management, vlan_ip:  10.195.0.1 255.255.255.192 }
  - { vlan_id: 101, description: Wireless, vlan_ip: 10.195.0.129 255.255.255.192  }
  - { vlan_id: 102, description: Guest, vlan_ip:  10.195.0.193 255.255.255.192 }
  - { vlan_id: 103, description: Wired, vlan_ip: 10.195.1.1 255.255.255.0  }
  - { vlan_id: 104, description: Voice, vlan_ip: 10.196.2.1 255.255.255.128 }
    
local_lan_range:
    10.195.0.0

vrf_default_gateway1:
    96.80.96.158
    
vrf_default_gateway2:
    12.110.251.217

circuit_1_ip:
    96.80.96.157 255.255.255.252
    
circuit_2_ip:
    12.110.251.216 255.255.255.248

tunnel_101_ip:
    10.195.252.3

tunnel_102_ip:
    10.195.253.3
    
hub_ip_101:
    10.195.252.1
    
hub_ip_102:
    10.195.253.1
    
local_loopback0_ip:
    10.195.255.3
    
asa_inside_interface_ip:
    10.195.0.70
    
asa_outside_interface_ip:
    10.195.0.66
  
vlan998:
    10.195.0.69
    
vlan999:
    10.195.0.65
    
dhcp_range_wired:
    10.195.113.0 /24
    
dhcp_excluded_range_wired:
    10.195.1.1 10.195.1.9
    
dhcp_default_router_wired:
    10.195.1.1
    
dhcp_range_management:
    10.195.0.0 /26
    
dhcp_excluded_range_management:
    10.195.0.1 10.195.0.9
    
dhcp_default_router_management:
    10.195.0.1
    
dhcp_range_wireless:
    10.195.0.128 /26
    
dhcp_excluded_range_wireless:
    10.195.0.129 10.195.1.132
    
dhcp_default_router_wireless:
    10.195.0.129
    
dhcp_range_guest:
    10.195.0.192 /26
    
dhcp_excluded_range_guest:
    10.195.0.193 10.195.0.195
    
dhcp_default_router_guest:
    10.195.0.193